### ISSUE TITLE
SNES Display Ratio

### ISSUE THREAD

**Issue by akhobbes** [fewtarius/351ELEC#41] opened 2020-12-08 17:22 UTC
Trying to keep games stretched to 16:9 or 3:2 full screen but retroarch defaults to 8:7 no matter what. I've tried changing global settings and creating/saving new retroarch cfg but nothing sticks. It's SO annoying. This was fine on global settings on previous versions, now it seems broken :(

**Comment by fewtarius** [comment] 2020-12-08 17:26
Duplicate of #38.

**Closed by fewtarius** 2020-12-08 17:26 UTC

**Comment by akhobbes** [comment] 2020-12-08 17:44
I disabled RGA scaling, still won't default to 16:9 or 3:2 on SNES. I noticed it won't save the retro cfg file.
